# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-4aa2b9f3-6eb6-4442-a58e-1c98abc967bc";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-4aa2b9f3-6eb6-4442-a58e-1c98abc967bc".device = "/dev/disk/by-uuid/4aa2b9f3-6eb6-4442-a58e-1c98abc967bc";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9B85-35E8";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-9f3b7c34-06ca-4c9d-91d8-64018e82263a"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
